### ISSUE TITLE
Manually show/hide selected nodes

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [UniFormal/TGView#45] opened 2018-04-13 15:33 UTC
Hi,

this is what an (ephemeral) MPD currently looks like. Pretty neat, right? ;)
![screenshot from 2018-04-13 17-31-01](https://user-images.githubusercontent.com/9729409/38743877-84c8805a-3f40-11e8-96ee-c75299ac0846.png)

It would be nice though if the included (grey blob) theories could go away, at least optionally and at least for MPDs. 

Thanks already!

**Comment by Shadow992** [comment] 2018-04-13 15:59
Are you able to share the URI or the graph? Because technically this looks like a duplicate of https://github.com/UniFormal/TGView/issues/18. However I will change this issue to something "similar", which just came to my mind! :)

**Comment by freifrauvonbleifrei** [comment] 2018-04-14 06:03
Yup, similar to  #18, but with the special case of tgview showing the directly includes of the graph nodes that it got by default - which is reasonable for theory graphs but should not be default for mpds, I think :)

**Comment by Shadow992** [comment] 2018-04-26 15:54
Implemented with https://github.com/UniFormal/TGView/commit/5aa9338da483d90720a621e6797962f40a68a98e

**Closed by Shadow992** 2018-04-26 15:54 UTC

**Comment by freifrauvonbleifrei** [comment] 2018-05-07 12:05
Dennis told me that for theory graphs, there was a design choice to show the direct includes of the theories displayed, even if they are not in the same namespace, such as `Strings` into `Meta` [in this example](https://mmt.mathhub.info/graphs/tgview.html?type=archivegraph&graphdata=Teaching/KRMT&highlight=null). 
This is very sensible for theory graphs (shows me how stuff is embedded into other stuff), but not necessarily for MPDs.
